-- Source of truth: backend/db/01_schema.sql
ALTER TABLE events ADD COLUMN IF NOT EXISTS event_status VARCHAR(30) NOT NULL DEFAULT 'not_started';
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_real_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_real_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_lat NUMERIC;
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_lon NUMERIC;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_lat NUMERIC;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_lon NUMERIC;
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_photo_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_photo_url TEXT;
